import Configuration from './indent.d'

const configuration:Configuration = {
	ruleId: `indent`,
	providerId: `eslint`,
	priority: `TASTE`,
	activate: true,
	options: [
		`tab`,
		{
			SwitchCase: 1,
			VariableDeclarator: 0,
			outerIIFEBody: 1,
			MemberExpression: 0,
			FunctionDeclaration: {
				parameters: 1,
				body: 1,
			},
			FunctionExpression: {
				parameters: 1,
				body: 1,
			},
			StaticBlock: {
				body: 1,
			},
			CallExpression: {
				arguments: 1,
			},
			ArrayExpression: 1,
			ObjectExpression: 1,
			ImportDeclaration: 1,
			flatTernaryExpressions: undefined,
			offsetTernaryExpressions: undefined,
			ignoredNodes: [
				`ConditionalExpression`,
				`TemplateLiteral > *`, // https://stackoverflow.com/a/53094449

				// it's a pity, but https://github.com/typescript-eslint/typescript-eslint/issues/1824
				`TSAbstractClassProperty`,
				`TSAbstractKeyword`,
				`TSAbstractMethodDefinition`,
				`TSAnyKeyword`,
				`TSArrayType`,
				`TSAsExpression`,
				`TSAsyncKeyword`,
				`TSBigIntKeyword`,
				`TSBooleanKeyword`,
				`TSCallSignatureDeclaration`,
				`TSClassImplements`,
				`TSConditionalType`,
				`TSConstructorType`,
				`TSConstructSignatureDeclaration`,
				`TSDeclareFunction`,
				`TSDeclareKeyword`,
				`TSEmptyBodyFunctionExpression`,
				`TSEnumDeclaration`,
				`TSEnumMember`,
				`TSExportAssignment`,
				`TSExportKeyword`,
				`TSExternalModuleReference`,
				`TSFunctionType`,
				`TSImportEqualsDeclaration`,
				`TSImportType`,
				`TSIndexedAccessType`,
				`TSIndexSignature`,
				`TSInferType`,
				`TSInterfaceBody`,
				`TSInterfaceDeclaration`,
				`TSInterfaceHeritage`,
				`TSIntersectionType`,
				`TSIntrinsicKeyword`,
				`TSLiteralType`,
				`TSMappedType`,
				`TSMethodSignature`,
				`TSModuleBlock`,
				`TSModuleDeclaration`,
				`TSNamedTupleMember`,
				`TSNamespaceExportDeclaration`,
				`TSNeverKeyword`,
				`TSNonNullExpression`,
				`TSNullKeyword`,
				`TSNumberKeyword`,
				`TSObjectKeyword`,
				`TSOptionalType`,
				`TSParameterProperty`,
				`TSParenthesizedType`,
				`TSPrivateKeyword`,
				`TSPropertySignature`,
				`TSProtectedKeyword`,
				`TSPublicKeyword`,
				`TSQualifiedName`,
				`TSReadonlyKeyword`,
				`TSRestType`,
				`TSStaticKeyword`,
				`TSStringKeyword`,
				`TSSymbolKeyword`,
				`TSTemplateLiteralType`,
				`TSThisType`,
				`TSTupleType`,
				`TSTypeAliasDeclaration`,
				`TSTypeAnnotation`,
				`TSTypeAssertion`,
				`TSTypeLiteral`,
				`TSTypeOperator`,
				`TSTypeParameter`,
				`TSTypeParameterDeclaration`,
				`TSTypeParameterInstantiation`,
				`TSTypePredicate`,
				`TSTypeQuery`,
				`TSTypeReference`,
				`TSUndefinedKeyword`,
				`TSUnionType`,
				`TSUnknownKeyword`,
				`TSVoidKeyword`,
			],
			ignoreComments: false,
		},
	],
}

export default configuration
